version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: "traefik"
    hostname: traefik_container
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # logging
      - --accesslog=true
      #- --log.level=DEBUG
      - --accesslog.filepath=/var/log/traefik.log
      - --accesslog.bufferingsize=100
      # create entrypoints
      - --entrypoints.www.address=:80/tcp
      - --entrypoints.traefik.address=:8080/tcp
      # urfd
      - --entrypoints.urfd-http.address=:80/tcp
      - --entrypoints.urfd-repnet.address=:8080/udp
      - --entrypoints.urfd-repnet.udp.timeout=86400s
      - --entrypoints.urfd-xlxcore.address=:10001/udp
      - --entrypoints.urfd-xlxcore.udp.timeout=86400s
      - --entrypoints.urfd-interlink.address=:10002/udp
      - --entrypoints.urfd-interlink.udp.timeout=86400s
      - --entrypoints.urfd-ysf.address=:42000/udp
      - --entrypoints.urfd-ysf.udp.timeout=86400s
      - --entrypoints.urfd-dextra.address=:30001/udp
      - --entrypoints.urfd-dextra.udp.timeout=86400s
      - --entrypoints.urfd-dplus.address=:20001/udp
      - --entrypoints.urfd-dplus.udp.timeout=86400s
      - --entrypoints.urfd-dcs.address=:30051/udp
      - --entrypoints.urfd-dcs.udp.timeout=86400s
      - --entrypoints.urfd-dmr.address=:8880/udp
      - --entrypoints.urfd-dmr.udp.timeout=86400s
      - --entrypoints.urfd-mmdvm.address=:62030/udp
      - --entrypoints.urfd-mmdvm.udp.timeout=86400s
      - --entrypoints.urfd-icom-terminal-1.address=:12345/udp
      - --entrypoints.urfd-icom-terminal-1.udp.timeout=86400s
      - --entrypoints.urfd-icom-terminal-2.address=:12346/udp
      - --entrypoints.urfd-icom-terminal-2.udp.timeout=86400s
      - --entrypoints.urfd-icom-dv.address=:40000/udp
      - --entrypoints.urfd-icom-dv.udp.timeout=86400s
      - --entrypoints.urfd-yaesu-imrs.address=:21110/udp
      - --entrypoints.urfd-yaesu-imrs.udp.timeout=86400s
    ports:
      # traefik ports
      - 80:80/tcp # The www port
      - 8080:8080/tcp # The Web UI (enabled by --api.insecure=true)
      # urfd ports
      - 80:80/tcp # http
      - 8080:8080/udp # repnet
      - 10001:10001/udp # xlxcore
      - 10002:10002/udp # xlx interlink
      - 42000:42000/udp # ysf
      - 30001:30001/udp # dextra
      - 20001:20001/udp # dplus
      - 30051:30051/udp # dcs
      - 8880:8880/udp # dmr
      - 62030:62030/udp # mmdvm
      - 12345:12345/udp # icom terminal 1
      - 12346:12346/udp # icom terminal 2
      - 40000:40000/udp # icom dv
      - 21110:21110/udp # yaesu imrs
    networks:
      - proxy
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  tcd:
    image: mfiscus/tcd:latest
    container_name: tcd
    hostname: tcd_container
    depends_on:
      traefik:
        condition: service_started
    networks:
      - proxy
    privileged: true
    restart: unless-stopped

  urfd:
    image: mfiscus/urfd:latest
    container_name: urfd
    hostname: urfd_container
    depends_on:
      traefik:
        condition: service_started
      tcd:
        condition: service_healthy
        restart: true
    labels:
      - "traefik.urfd-http.rule=HostRegexp:your_domain.com,{catchall:.*}"
      - "traefik.urfd-http.priority=1"
      - "traefik.docker.network=docker_proxy"
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # The domain the service will respond to
      - "traefik.http.routers.urfd-http.rule=Host(`your_domain.com`)"
      # Allow request only from the predefined entry point named "urfd-http"
      - "traefik.http.routers.urfd-http.entrypoints=urfd-http"
      # Specify port
      - "traefik.http.services.urfd-http.loadbalancer.server.port=80"
      # test alternate http port
      - "traefik.http.routers.urfd-http.service=urfd-http"
      # UDP routers
      # repnet
      - "traefik.udp.routers.urfd-repnet.entrypoints=urfd-repnet"
      - "traefik.udp.routers.urfd-repnet.service=urfd-repnet"
      - "traefik.udp.services.urfd-repnet.loadbalancer.server.port=8080"
      # xlxcore
      - "traefik.udp.routers.urfd-xlxcore.entrypoints=urfd-xlxcore"
      - "traefik.udp.routers.urfd-xlxcore.service=urfd-xlxcore"
      - "traefik.udp.services.urfd-xlxcore.loadbalancer.server.port=10001"
      # xlx interlink
      - "traefik.udp.routers.urfd-interlink.entrypoints=urfd-interlink"
      - "traefik.udp.routers.urfd-interlink.service=urfd-interlink"
      - "traefik.udp.services.urfd-interlink.loadbalancer.server.port=10002"
      # urfd-ysf
      - "traefik.udp.routers.urfd-ysf.entrypoints=urfd-ysf"
      - "traefik.udp.routers.urfd-ysf.service=urfd-ysf"
      - "traefik.udp.services.urfd-ysf.loadbalancer.server.port=42000"
      # urfd-dextra
      - "traefik.udp.routers.urfd-dextra.entrypoints=urfd-dextra"
      - "traefik.udp.routers.urfd-dextra.service=urfd-dextra"
      - "traefik.udp.services.urfd-dextra.loadbalancer.server.port=30001"
      # urfd-dplus
      - "traefik.udp.routers.urfd-dplus.entrypoints=urfd-dplus"
      - "traefik.udp.routers.urfd-dplus.service=urfd-dplus"
      - "traefik.udp.services.urfd-dplus.loadbalancer.server.port=20001"
      # dcs
      - "traefik.udp.routers.urfd-dcs.entrypoints=urfd-dcs"
      - "traefik.udp.routers.urfd-dcs.service=urfd-dcs"
      - "traefik.udp.services.urfd-dcs.loadbalancer.server.port=30051"
      # dmr
      - "traefik.udp.routers.urfd-dmr.entrypoints=urfd-dmr"
      - "traefik.udp.routers.urfd-dmr.service=urfd-dmr"
      - "traefik.udp.services.urfd-dmr.loadbalancer.server.port=8880"
      # mmdvm
      - "traefik.udp.routers.urfd-mmdvm.entrypoints=urfd-mmdvm"
      - "traefik.udp.routers.urfd-mmdvm.service=urfd-mmdvm"
      - "traefik.udp.services.urfd-mmdvm.loadbalancer.server.port=62030"
      # icom-terminal-1
      - "traefik.udp.routers.urfd-icom-terminal-1.entrypoints=urfd-icom-terminal-1"
      - "traefik.udp.routers.urfd-icom-terminal-1.service=urfd-icom-terminal-1"
      - "traefik.udp.services.urfd-icom-terminal-1.loadbalancer.server.port=12345"
      # icom-terminal-2
      - "traefik.udp.routers.urfd-icom-terminal-2.entrypoints=urfd-icom-terminal-2"
      - "traefik.udp.routers.urfd-icom-terminal-2.service=urfd-icom-terminal-2"
      - "traefik.udp.services.urfd-icom-terminal-2.loadbalancer.server.port=12346"
      # icom-dv
      - "traefik.udp.routers.urfd-icom-dv.entrypoints=urfd-icom-dv"
      - "traefik.udp.routers.urfd-icom-dv.service=urfd-icom-dv"
      - "traefik.udp.services.urfd-icom-dv.loadbalancer.server.port=40000"
      # yaesu-imrs
      - "traefik.udp.routers.urfd-yaesu-imrs.entrypoints=urfd-yaesu-imrs"
      - "traefik.udp.routers.urfd-yaesu-imrs.service=urfd-yaesu-imrs"
      - "traefik.udp.services.urfd-yaesu-imrs.loadbalancer.server.port=21110"
    environment:
      # only set CALLHOME to true once your are certain your configuration is correct
      # make sure you backup your callinghome.php file (which should be located on the docker host in /opt/urfd/) 
      CALLHOME: 'false' 
      CALLSIGN: 'your_callsign'
      EMAIL: 'your@email.com'
      URL: 'your_domain.com'
      PORT: '80'
      XLXNUM: 'XLX000'
      COUNTRY: 'United States'
      DESCRIPTION: 'My urfd-docker reflector'
      # Define how many modules you require
      MODULES: '4'
      # Name your modules however you like (container only supports naming first 4)
      MODULEA: 'Main'
      MODULEB: 'D-Star'
      MODULEC: 'DMR'
      MODULED: 'YSF'
      TZ: 'UTC'
    networks:
      - proxy
    volumes:
      # local directory where state and config files (including callinghome.php) will be saved
      - /opt/urfd:/config
    restart: unless-stopped