version: '3.8'

services:
  mrefd:
    image: mfiscus/mrefd:latest
    container_name: mrefd
    hostname: mrefd_container
    environment:
      TZ: 'UTC'
      EMAILADDR: 'your@email.com'
      COUNTRY: 'US'
      DASHBOARDURL: 'your_domain.com'
      PORT: '80'
      CALLSIGN: 'M17-???'
      MODULES: 'A'
      SPONSOR: 'Chandler Hams'
      MULTICLIENT: 'true'
      BOOTSTRAP: 'xlx757.openquad.net'
    volumes:
      - /opt/mrefd:/config
    restart: unless-stopped
